### PR TITLE
update functionality of the todo and improve css to provide better us…

### LINKED ISSUE #3: Want to add search bar and improve css

### PR DESCRIPTION
**Pull request by avishaan24**
I try lot to change and improve the functionality of the todo

### CODE REVIEW

**Review by IumoInfinium — APPROVED** [review]
@avishaan24 those are some major changes, thanks for your time 😄

**Comment by IumoInfinium** [comment]
Hii @avishaan24 
Seems like there are some UI issues and the functionality of todo, seems kinda broken.
Can you check it out? Help appreciated.

**Comment by IumoInfinium** [comment]
For now, I am reverting it back to previous state.

**Comment by avishaan24** [comment]
Hii @IumoInfinium can you explain briefly what UI and functionality of to-do was not working. It would be better for me to solve the issue

**Comment by IumoInfinium** [comment]
Hey @avishaan24 you can check the issues sections for this.

**Comment by avishaan24** [comment]
Hii @IumoInfinium,
Solution to the issues raised by you 
       * I mistakenly diminished the size of github icon due to provide responsiveness.
       * And at first explain what I have done, In the top after to-do list there is search bar from where  anyone can search any of their tasks  then as you made a windows reloader button I didn't make any changes on that, then there is input box from where anyone can add their new tasks and after that add-task button which is used to add the task. I think there is no two boxes to add new tasks.
       * Now, I explain the function of delete, edit/ save button. As whenever anyone add task from above input then the task added in the list but it's only in reading mode, noone can edit without pressing the edit button when anyone press the edit button then the button automatically changes to save button and the task is in write mode from which anyone edit their task and save it. After pressing the save button, button changes to edit button and task changes to readonly mode & delete button is used to delete the tasks.
       * As you add changing background so providing any fixed colour border didn't work on some images and look likes eye catching. So, my suggestion is to fixed the background image and then add border colour to improve UI.
       * And I change all text-alignment to center.
That's all from my side.
Waiting for your suggestion.
Thanks

**Pull request merged**
